<?php

namespace It\CsvImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDataRepository extends EntityRepository
{

}
